### ISSUE TITLE
LastMod date doesn't pass format validation in Google Webmaster

### ISSUE THREAD

**Issue by liamlaverty** [stormid/Sitemapify#3]
When submitting a generated XML document to Google Webmaster tools, I get the error "An invalid date was found. Please fix the date or formatting before resubmitting."

I can see it's set here https://github.com/stormid/Sitemapify/blob/bcee86c5358ec98e3c08b497eca55c1f2243c950/src/Sitemapify/Extensions/SitemapUrlExtensions.cs#L15, but I'm not sure how to update it to use a differnet format.

I didn't want to just change it to `.ToString("yyyy-MM-dd");` as it'd break it for others who have the correct culture settings. 

![image](https://user-images.githubusercontent.com/7046713/27595208-f13211f6-5b53-11e7-973d-122f1f7a50cf.png)

**Comment by Philo** [comment]
Looks like the `lastmod` property should have been a `DateTimeOffset` so that it will be output with timezone information for the google webmaster tools validation.

I'll take a look at sorting that for you.

**Comment by Philo** [comment]
Just verifying this against the sitemaps schema definition and I'm surprised Google is having an issue:

https://www.sitemaps.org/protocol.html

states that the `lastmod` value should be https://www.w3.org/TR/NOTE-datetime

**Comment by Philo** [comment]
@liamlaverty,

Can you check whether the update made in this release corrects the webmaster tools validation:

https://github.com/stormid/Sitemapify/releases/tag/0.5.0

Regards

**Comment by liamlaverty** [comment]
hey @Philo ,

Google's accepted the sitemap generated by the 0.5.0 version 

![image](https://user-images.githubusercontent.com/7046713/27793387-ba96ab9c-5ff5-11e7-91ea-f1598786fae4.png)


Thanks!
Liam

**Comment by Philo** [comment]
Great, thanks for raising the issue and testing the solution.
