### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by kantan-florian** [stormid/Sitemapify#5]
Hi there! Google is complaining that the priority is "1,0". I guess the problem is the comma and it expects a dot as separator. I am not sure why, the servers are running an english OS and google should send english locale info - but howevery - can you fix the string representation for doubles to "figures dot decimals"?

Thanks... the rest works quite well ;)

Florian

**Comment by Philo** [comment]
I'm just releasing v0.5.2, this should correct the problem and ensure that culture is ignored when string formatting the `priority`.
